# Site
baseurl: ""
permalink: /:title
title: Judson L Moore
tagline: Author and travel addict
description: Do you want to experience the world? I encourage you to get an early start at living a full and adventurous life by providing tips for living your "what if" while young.
url: "https://www.judsonlmoore.com"
author: Judson L Moore
logo: 
lang: en_US
twitter:
  username: judsonlmoore
  card: summary_large_image
facebook:
  app_id: 990949061035215
  publisher: https://www.facebook.com/JudsonLMooreBlog/
  admins: judsonlmoore
favicon: /assets/images/favicon.png
webmaster_verifications:
  google: 3MN-XApFrgWYSpGop2aNPX3eHkQtKupxl-OltwME23o
  bing: 1571295b1311496094a646cca481014e
  yandex: df106ee154e1faa4 
disqus: "judsonlmoore"
mailchimp-list: "https://judsonlmoore.us2.list-manage.com/subscribe/post?u=fcb5f983e8f1c7cb022f4353b&amp;id=2d85dca5fe"

# other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

gems:
  - jekyll-paginate-v2

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank

include: 
  - _pages

exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
      author: "judsonlmoore"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-single"
      is_post: true
  - scope:
      path: '_pages'
    values:
      layout: "autopage_category"
      permalink: /:basename/
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "blog-author"

# jekyll-cloudinary
cloudinary:
  cloud_name: judsonlmoore-com
  only_prod: true
  verbose: false
  presets:
    default:
      gravity: auto
      crop: fill
      focus: auto
      min_width: 256
      max_width: 1024
      figure: auto
      attributes:
        class: "img-fluid"
        loading: "lazy"
    thumbnail:
      min_width: 64
      min_height: 64
      max_width: 512
      max_height: 512
    post-avatar:
      min_width: 70
      min_height: 70
      max_width: 70
      max_height: 70
      steps: 1
      attributes:
        class: "avatar-xl rounded-circle mr-3 img-fluid"

# algolia seaech api 
algolia:
  application_id: 7NL4THI97T
  index_name: judsonlmoore.com
  search_only_api_key: 32a647216673c47b6e482d43e5c289a3

# minification
compress_html:  
  clippings: all  
  comments: ["<!-- ", " -->"] 
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th] 
  profile: false 
  blanklines: false 
  ignore: 
    envs: []

#contact
contact:
  speaking: assistant@jlm.me
  other: contact@jlm.me
  whatsapp: +1.310.571.5210

# links 
links:
  facebook: https://www.facebook.com/judsonlmooreblog
  twitter: https://twitter.com/judsonlmoore
  linkedin: https://www.linkedin.com/in/judsonlmoore
  instagram: https://www.instagram.com/judsonlmoore/
  youtube: https://www.youtube.com/judsonlmoore
  github: https://github.com/judsonlmoore

# Pagination Settings
pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

autopages:
  enabled: true
  categories: 
    layouts: 
      - 'autopage_category.html'
    title: 'Posts in category :cat'
    permalink: '/category/:cat/'
    slugify:
      mode: 'default'
      case: true