# Site
title: Judson L Moore
tagline: Author and travel addict
description: Do you want to experience the world? I encourage you to get an early start at living a full and adventurous life by providing tips for living your "what if" \#WhileYoung.
url: "https://www.judsonlmoore.com"
image-path: /assets/images/
name: Judson L Moore
author: Judson L Moore
logo: /assets/images/avatar-judsonlmoore.png
lang: en_US
twitter:
  username: judsonlmoore
  card: summary_large_image
facebook:
  app_id: 990949061035215
  publisher: https://www.facebook.com/JudsonLMooreBlog/
  admins: judsonlmoore
favicon: assets/images/favicon.png
social:
  name: Judson L Moore
  links:
    - https://twitter.com/judsonlmoore
    - https://www.facebook.com/judsonlmooreblog
    - https://www.linkedin.com/in/judsonlmoore
    - https://github.com/judsonlmoore
    - https://www.instagram.com/judsonlmoore/
webmaster_verifications:
  google: 3MN-XApFrgWYSpGop2aNPX3eHkQtKupxl-OltwME23o
  bing: 1571295b1311496094a646cca481014e
  yandex: df106ee154e1faa4 
baseurl: ""
disqus: "judsonlmoore"
mailchimp-list: "https://judsonlmoore.us2.list-manage.com/subscribe/post?u=fcb5f983e8f1c7cb022f4353b&amp;id=2d85dca5fe"
include: ["_pages"]
permalink: /:title/

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      image: /assets/images/2019/11/judsonlmoore-holding-exponential-happiness.jpg

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-include-cache
  - jekyll-sitemap

sass:
  load_paths:
    - _sass
    - node_modules

# _config.yml
# Note: Your API key will be read from an ENV variable
algolia:
  application_id: '7NL4THI97T'
  index_name:     'judsonlmoore.com'
  search_only_api_key: 32a647216673c47b6e482d43e5c289a3

# Pagination
paginate: 12
paginate_path: "/blog/page-:num/"

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

# Other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

exclude:
  - .jekyll-cache
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - gemfiles/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - node_modules/

feed:
  path: atom.xml
  excerpt_only: true

compress_html:  
  clippings: all  
  comments: ["<!-- ", " -->"] 
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th] 
  profile: false 
  blanklines: false 
  ignore: 
    envs: []

cloudinary:
  cloud_name: judsonlmoore-com
  verbose: false
  only_prod: true
  presets:
    default:
      gravity: auto
      crop: fill
      focus: auto
      quality: auto
      min_width: 64
      max_width: 1024
      fallback_max_width: 806
      steps: 5
      attributes:
        class: img-fluid
        loading: auto