# Site
title: Judson L Moore
tagline: Author and travel addict
description: Do you want to experience the world? I encourage you to get an early start at living a full and adventurous life by providing tips for living your "what if" while young.
url: "https://www.judsonlmoore.com"
image-path: /assets/images/
name: Judson L Moore
author: Judson L Moore
logo: /assets/images/avatar-judsonlmoore.png
lang: en_US
twitter:
  username: judsonlmoore
  card: summary_large_image
facebook:
  app_id: 990949061035215
  publisher: https://www.facebook.com/JudsonLMooreBlog/
  admins: judsonlmoore
favicon: /assets/images/favicon.png
social:
  name: Judson L Moore
  links:
    - https://twitter.com/judsonlmoore
    - https://www.facebook.com/judsonlmooreblog
    - https://www.linkedin.com/in/judsonlmoore
    - https://github.com/judsonlmoore
    - https://www.instagram.com/judsonlmoore/
webmaster_verifications:
  google: 3MN-XApFrgWYSpGop2aNPX3eHkQtKupxl-OltwME23o
  bing: 1571295b1311496094a646cca481014e
  yandex: df106ee154e1faa4 
baseurl: ""
disqus: "judsonlmoore"
mailchimp-list: "https://judsonlmoore.us2.list-manage.com/subscribe/post?u=fcb5f983e8f1c7cb022f4353b&amp;id=2d85dca5fe"
include: ["_pages"]
permalink: /:title/

collections:
  authors:
    output: false
  travel-guides:
    output: true

defaults:
  - scope:
      path: ""
    values:
      author: "judsonlmoore"
      layout: "page"
      image: /assets/images/2019/11/judsonlmoore-holding-exponential-happiness.jpg
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "travel-guides"
    values:
      layout: "fullwidth-hero"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-target-blank

# jekyll-cloudinary
cloudinary:
  cloud_name: judsonlmoore-com
  only_prod: true
  presets:
    default:
      gravity: auto
      crop: fill
      focus: auto
      min_width: 256
      max_width: 1024
      figure: never
      attributes:
        class: "img-fluid"
        loading: "lazy"
    thumbnail:
      min_width: 64
      min_height: 64
      max_width: 512
      max_height: 512
      attributes:
        class: "img-fluid"
        loading: "lazy"

sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed

# excludes
exclude:
  - .jekyll-cache
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - gemfiles/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - node_modules/

# seaech api 
algolia:
  application_id: 7NL4THI97T
  index_name: judsonlmoore.com
  search_only_api_key: 32a647216673c47b6e482d43e5c289a3

# jekyll-paginate
paginate: 12
paginate_path: "/blog/page-:num/"

# jekyll-archives
jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/archives/year/:year/'
    month: '/archives/month/:year-:month/'
    tag: '/archives/tag/:name/'
    day: '/archives/:year/:month/:day/'
    category: '/archives/category/:name/'

# jekyll-feed
feed:
  path: atom.xml
  excerpt_only: true

# other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# minification
compress_html:  
  clippings: all  
  comments: ["<!-- ", " -->"] 
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th] 
  profile: false 
  blanklines: false 
  ignore: 
    envs: []
