# Site
title: Judson L Moore
name: Judson L Moore
description: Author and travel addict
url: https://nonprod.judsonlmoore.com
image-path: /assets/images/
author: judsonlmoore
twitter:
  username: judsonlmoore
  card: summary_large_image
facebook:
  app_id: 611458568990674
  publisher:
  admins:
logo: assets/images/jlm-logo-full-bw-dark.png
favicon: assets/images/favicon.png
social:
  name: Judson L Moore
  links:
    - https://twitter.com/judsonlmoore
    - https://www.facebook.com/judsonlmooreblog
    - https://www.linkedin.com/in/judsonlmoore
    - https://github.com/judsonlmoore
    - https://www.instagram.com/judsonlmoore
  google: 3MN-XApFrgWYSpGop2aNPX3eHkQtKupxl-OltwME23o
  bing: 1571295b1311496094a646cca481014e
  alexa:
  yandex: df106ee154e1faa4
  baidu:
baseurl: ""
# google_analytics: 'UA-12358141-4'
disqus: "judsonlmoore"
mailchimp-list: "https://judsonlmoore.us2.list-manage.com/subscribe/post?u=fcb5f983e8f1c7cb022f4353b&amp;id=2d85dca5fe"
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  judsonlmoore:
    name: Judson L Moore
    display_name: Judson L Moore
    avatar: assets/images/avatars/avatar-judsonlmoore.jpg
    email: judson@judsonlmoore.com
    web: https://www.judsonlmoore.com
    twitter: https://twitter.com/judsonlmoore
    description: "Travel addict. Ambitious about making the world a better place. Writing what I learn along the way."
  bobmoore:
    name: Bob Moore
    display_name: Bob Moore
    gravatar: 33cd6f3235b9b5e27d9a35d328fddd7b
    description: Bob Moore is a retired sociologist living in Bryan, Texas. A graduate of Louisiana State University with a doctorate from the University of Kentucky, his has been author or co-author of hundreds of peer-reviewed medical studies. He is the smartest person Judson Moore has ever met, and coincidentally, Bob is Judson's father.
  jenniferchang:
    name: Jennifer Chang
    display_name: Jennifer Chang
    gravatar:
    description: I'm a compulsive writer, creative strategist, and experience junkie currently eating my way through New York City and seeking the meaning of life (among other things).
    twitter: https://www.twitter.com/jayemsey
    instagram: https://www.instagram.com/jayemsey
    linkedin: https://www.linkedin.com/in/jayemsey
    web: https://www.jayemsey.com/
    youtube: https://www.youtube.com/user/jayemsey
  kellybranyik:
    name: Kelly Branyik
    display_name: Kelly Branyik
    gravatar:
    description: Kelly Branyik is a Returned Peace Corps Volunteer who served from 2014-2016 in Chongqing, China. She currently resides in Colorado Springs where she works as a TV and Radio commercial scriptwriter for a local advertising agency. Kelly is a published author of the book, "It Depends - A Guide to Peace Corps.” She still shares her stories of Peace Corps on her blog, Propitious Panda in hopes to inspire people to take the journey.
    facebook: https://www.facebook.com/propitiouspanda/
    twitter: https://www.twitter.com/propitiouspanda
    instagram: https://www.instagram.com/propitiouspanda
    pintrest: https://www.pinterest.com/travelbranyik/
    web: https://travelbranyik.com/
    youtube: https://www.youtube.com/channel/UC8SXQMMzRJKKgDHtoBbGfYg
  tarahmason:
    name: Tarah Mason
    gravatar: 5f34aa736d5e05203f81bd1463ff3514
    display_name: Tarah Mason
    description: I am a California native and a graduate from the University of Alabama (roll tide)! I discovered my love for travel while studying abroad in Barcelona, Spain and haven’t been able to sit still since. After graduation, I moved to Thailand to teach English and travel Southeast Asia. Basically, I’m a normal 23-year-old, trying to see the world before her mom guilt trips her into coming home!
    facebook: https://www.facebook.com/travelwithtarah/
    instagram: https://www.instagram.com/tarahmason/
    pintrest: https://www.pinterest.com/tarahmason/
    linkedin: https://www.linkedin.com/in/tarahmason/
    web: https://www.travelwithtarah.com/
    youtube:
  visitbrazil:
    name: Visit Brazil
    display_name: Visit Brazil
    gravatar:
    description: Embratur is the special agency of the Ministry of Tourism responsible for the promotion, marketing and trade support of Brazilian destinations, tourism products and services in the international market. Among the market-driven platforms and programs utilized to increase inbound visitor travel to the country is the official website of tourism of Brasil, VisitBrasil.
    facebook: https://www.facebook.com/VisitBrasil
    twitter: https://www.twitter.com/VisitBrasil
    instagram: https://www.instagram.com/visitbrasil/
    web: https://www.visitbrasil.com/
    youtube: https://www.youtube.com/visitbrasil

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-include-cache

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude:
  - .jekyll-cache
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

cloudinary_url: https://res.cloudinary.com/judsonlmoore-com/image/fetch/
img_transform_post_feature: c_fill,g_auto,f_auto,q_auto,w_800

#jekyll-cloudinary https://nhoizey.github.io/jekyll-cloudinary/
cloudinary:
  cloud_name: judsonlmoore-com
  only_prod: true
  verbose: true
  #origin_url:
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 100vw"
      figure: auto
      attributes:
        class: "post-image full"
        loading: "auto"
        style: "height: auto"
    half:
      min_width: 320
      max_width: 1600
      max_height: 100%
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 25rem) 25rem, 50vw"
      figure: auto
      attributes:
        class: "post-image half"
        loading: "auto"
        style: "height: auto"
    post-hero:
      min_width: 320
      max_width: 800
      max_height: 100%
      fallback_max_width: 800
      steps: 3
      sizes: "(min-width: 25rem) 25rem, 50vw"
      figure: auto
      attributes:
        class: "featured-image img-fluid"
        loading: "auto"
        style: "height: auto"
    jumbotron:
      min_width: 320
      max_width: 1600
      max_height: 100%
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 25rem) 25rem, 50vw"
      figure: auto
      attributes:
        class: "post-image half"
        loading: "auto"
        style: "height: auto"
