# Site
title: Judson L Moore
name: Judson L Moore
description: American Author and travel addict
url: https://www.judsonlmoore.com
author: judsonlmoore
twitter:
  username: judsonlmoore
  card: summary_large_image
facebook:
  app_id: 611458568990674
  publisher:
  admins:
logo: assets/images/jlm-logo-full-bw-dark.png
favicon: "assets/images/favicon.png"
social:
  name: Judson L Moore
  links:
    - https://twitter.com/judsonlmoore
    - https://www.facebook.com/judsonlmooreblog
    - https://www.linkedin.com/in/judsonlmoore
    - https://github.com/judsonlmoore
    - https://www.instagram.com/judsonlmoore
  google: 3MN-XApFrgWYSpGop2aNPX3eHkQtKupxl-OltwME23o
  bing: 1571295b1311496094a646cca481014e
  alexa:
  yandex: df106ee154e1faa4
  baidu:
baseurl: ""
# google_analytics: 'UA-12358141-4'
disqus: "judsonlmoore"
mailchimp-list: "https://judsonlmoore.us2.list-manage.com/subscribe/post?u=fcb5f983e8f1c7cb022f4353b&amp;id=2d85dca5fe"
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  judsonlmoore:
    name: Judson L Moore
    display_name: Judson L Moore
    gravatar: 8b6eff6e1152352a262b6276e3685350
    email: judson@judsonlmoore.com
    web: https://www.judsonlmoore.com
    twitter: https://twitter.com/judsonlmoore
    description: "Travel addict. Ambitious about making the world a better place. Writing what I learn along the way."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
# Cloudinary
# Learn More https://github.com/nhoizey/jekyll-cloudinary
# cloudinary:
#   cloud_name: judsonlmoore-com
#   only_prod: true
#   verbose: true
#   # origin_url: https://cdn.judsonlmoore.com
#   presets:
#     default:
#       min_width: 320
#       max_width: 1600
#       fallback_max_width: 800
#       steps: 5
#       sizes: "(min-width: 50rem) 50rem, 90vw"
