# Site
name: "Judson L Moore"
title: "American Author and travel addict."
description: "Travel guides and inspiration to follow your dreams and do it while you're young, from author and travel addict, Judson L Moore."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: ''
# google_analytics: 'UA-12358141-4'
disqus: 'judsonlmoore'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: judsonlmoore
    display_name: Judson L Moore
    gravatar: 8b6eff6e1152352a262b6276e3685350
    email: judson@judsonlmoore.com
    web: https://www.judsonlmoore.com
    twitter: https://twitter.com/judsonlmoore
    description: "I didn’t have many extraordinary advantages growing up, but what I did have was the encouragement of those older than me saying, “do it while you’re young.” One day, when I was 17, that advice stuck and I started traveling the world. I haven’t stopped and now half a lifetime later, I want to tell the world what I’ve learned and how YOU can live an adventurous and prosperous life!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

# Cloudinary 
# Learn More https://github.com/nhoizey/jekyll-cloudinary
cloudinary:
  cloud_name: judsonlmoore-com
  only_prod: true
  verbose: true
  # origin_url: https://cdn.judsonlmoore.com
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"