# Site
title: Judson L Moore
tagline: Author and travel addict
description: Do you want to experience the world? I encourage you to get an early start at living a full and adventurous life by providing tips for living your "what if" while young.
url: "https://www.judsonlmoore.com"
image-path: /assets/images/
name: Judson L Moore
author: Judson L Moore
logo: /assets/images/avatar-judsonlmoore.png
lang: en_US
twitter:
  username: judsonlmoore
  card: summary_large_image
facebook:
  app_id: 990949061035215
  publisher: https://www.facebook.com/JudsonLMooreBlog/
  admins: judsonlmoore
favicon: /assets/images/favicon.png
social:
  name: Judson L Moore
  links:
    - https://twitter.com/judsonlmoore
    - https://www.facebook.com/judsonlmooreblog
    - https://www.linkedin.com/in/judsonlmoore
    - https://github.com/judsonlmoore
    - https://www.instagram.com/judsonlmoore/
webmaster_verifications:
  google: 3MN-XApFrgWYSpGop2aNPX3eHkQtKupxl-OltwME23o
  bing: 1571295b1311496094a646cca481014e
  yandex: df106ee154e1faa4 
baseurl: ""
disqus: "judsonlmoore"
mailchimp-list: "https://judsonlmoore.us2.list-manage.com/subscribe/post?u=fcb5f983e8f1c7cb022f4353b&amp;id=2d85dca5fe"
include: ["_pages"]
permalink: /:title

collections:
  authors:
    output: true
  travel-guides:
    output: true

defaults:
  - scope:
      path: ""
    values:
      author: "judsonlmoore"
      layout: "page"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "blog-author"
  - scope:
      path: ""
      type: "travel-guides"
    values:
      layout: "fullwidth-hero"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-target-blank

# jekyll-cloudinary
cloudinary:
  cloud_name: judsonlmoore-com
  only_prod: true
  verbose: false
  presets:
    default:
      gravity: auto
      crop: fill
      focus: auto
      min_width: 256
      max_width: 1024
      figure: auto
      attributes:
        class: "img-fluid"
        loading: "lazy"
    thumbnail:
      min_width: 64
      min_height: 64
      max_width: 512
      max_height: 512
    postbox:
      min_width: 288
      min_height: 198
      max_width: 354
      max_height: 243
      attributes:
<<<<<<< Updated upstream
        class: "img-fluid"
        loading: "lazy"
    featured:
      min_width: 64
      min_height: 64
      max_width: 512
      max_height: 512
      attributes:
        class: "img-fluid"
        loading: "lazy"
    card-img-top:
      min_width: 64
      min_height: 64
      max_width: 512
      max_height: 512
      attributes:
        class: "img-fluid"
        loading: "lazy" 

=======
        class: "rounded w-100"
    post-avatar:
      min_width: 64
      min_height: 64
      max_width: 64
      max_height: 64
      steps: 1
      attributes:
        class: "avatar-xl rounded-circle mr-3"
>>>>>>> Stashed changes

sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed

gems:
  - jekyll-paginate-v2

# excludes
exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - coach-theme/

# seaech api 
algolia:
  application_id: 7NL4THI97T
  index_name: judsonlmoore.com
  search_only_api_key: 32a647216673c47b6e482d43e5c289a3

# jekyll-archives
jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/archives/year/:year/'
    month: '/archives/month/:year-:month/'
    tag: '/archives/tag/:name/'
    day: '/archives/:year/:month/:day/'
    category: '/archives/category/:name/'

# jekyll-feed
feed:
  path: atom.xml
  excerpt_only: true
  posts_limit: 1000
  collections:
    posts:
      path: "/posts.xml"
  categories:
    - news
    - updates

# other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# minification
compress_html:  
  clippings: all  
  comments: ["<!-- ", " -->"] 
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th] 
  profile: false 
  blanklines: false 
  ignore: 
    envs: []

# links 
links:
  facebook: https://www.facebook.com/judsonlmooreblog
  twitter: https://twitter.com/judsonlmoore
  linkedin: https://www.linkedin.com/in/judsonlmoore
  instagram: https://www.instagram.com/judsonlmoore/
  youtube: https://www.youtube.com/judsonlmoore
  github: https://github.com/judsonlmoore


############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: false

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 9

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page-:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  # title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
    extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
    indexpage: 'index'

############################################################


############################################################
# Site configuration for the Auto-Pages feature
# The values here represent the defaults if nothing is set
autopages:

  # Site-wide kill switch, disable here and it doesn't run at all 
  enabled: false

  # Category pages, omit entire config element to disable
  categories: 
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts: 
      - 'autopage_category.html'
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    # title: ':title - page :num'
    # Optional, the permalink for the  pagination page (:cat is replaced), 
    # the pagination permalink path is then appended to this permalink structure
  # permalink: '/:cat'
    slugify:
      mode: 'default'   # :cat is slugified. Modes: default, raw, pretty, ascii, latin
      case: false       # Whether to replace all uppercase letters with their lowercase counterparts

  # Collection pages, omit to disable
  collections:
    layouts: 
      - 'autopage_collection.html'
    title: ':coll' # :coll is replaced by the collection name
    # permalink: '/:coll'
    slugify:
      mode: 'default'   # :coll is slugified.
      case: false 
  
  # Tag pages, omit to disable
  tags:
    layouts: 
      - 'autopage_tags.html'
    title: ':tag' # :tag is replaced by the tag name
    # permalink: '/:tag'
    slugify:
      mode: 'default'   # :tag is slugified.
      case: false
