# Site
title: Judson L Moore
name: Judson L Moore
description: Author and travel addict
url: "https://www.judsonlmoore.com"
image-path: /assets/images/
author: judsonlmoore
twitter:
  username: judsonlmoore
  card: summary_large_image
facebook:
  app_id: 611458568990674
  publisher:
  admins:
logo: assets/images/jlm-logo-full-bw-dark.png
favicon: assets/images/favicon.png
social:
  name: Judson L Moore
  links:
    - https://twitter.com/judsonlmoore
    - https://www.facebook.com/judsonlmooreblog
    - https://www.linkedin.com/in/judsonlmoore
    - https://github.com/judsonlmoore
    - https://www.instagram.com/judsonlmoore
  google: 3MN-XApFrgWYSpGop2aNPX3eHkQtKupxl-OltwME23o
  bing: 1571295b1311496094a646cca481014e
  alexa:
  yandex: df106ee154e1faa4
  baidu:
baseurl: ""
disqus: "judsonlmoore"
mailchimp-list: "https://judsonlmoore.us2.list-manage.com/subscribe/post?u=fcb5f983e8f1c7cb022f4353b&amp;id=2d85dca5fe"
include: ["_pages"]
permalink: /:title/

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-include-cache
  - jekyll-sitemap

sass:
  load_paths:
    - _sass
    - node_modules

# Pagination
paginate: 6
paginate_path: /page:num/

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

# Other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

exclude:
  - .jekyll-cache
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - node_modules

compress_html:  
  clippings: all  
  comments: ["<!-- ", " -->"] 
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th] 
  profile: false 
  blanklines: false 
  ignore: 
    envs: []

cloudinary:
  cloud_name: judsonlmoore-com
  verbose: false
  only_prod: true
  presets:
    default:
      gravity: auto
      crop: fill
      focus: auto
      quality: auto
      min_width: 150
      max_width: 1200
      fallback_max_width: 800
      steps: 5
      figure: auto
      attributes:
        class: img-fluid
        loading: lazy
    featured-box-img-cover:
      attributes:
        class: featured-box-img-cover img-fluid
        min_width: 185
        min_hight: 350
        max_width: 510
        max_height: 360
        fallback_max_width: 510
    featured:
      attibutes:
        class: featured-image img-fluid img-fluid
        min_width: 315
        min_hight: 210
        max_width: 760
        max_height: 450
    author-thumb: 
      steps: 2
      attributes: 
        class: author-thumb img-fluid
        min_width: 40
        min_hight: 40
        max_width: 170
        max_height: 170
        fallback_max_width: 72