name: Twitter Promoter

on:
  schedule:
    # 10 AM and 3 PM Everyday
    - cron: "00 10,15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Blog Promoter
      uses: actions/checkout@v2
      with:
        repository: khalidabuhakmeh/BlogPromoter

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'

    - name: Run Promoter
      env: 
        twitter_account: '@judsonlmoore'
        blog_feed_url: 'https://judsonlmoore.com/atom.xml'
        twitter_access_token: ${{ secrets.twitter_access_token }}
        twitter_access_token_secret: ${{ secrets.twitter_access_token_secret }}
        twitter_consumer_key: ${{ secrets.twitter_consumer_key }}
        twitter_consumer_secret: ${{ secrets.twitter_consumer_secret }}
      run: dotnet run -c Release